version: '3'

services:
  wp:
    image: wordpress:latest
    container_name: wp
    ports:
      - 127.0.0.1:8000:80 # change ip if required
    volumes:
      - ./secrets/:/run/secrets
      - ./config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - wp_data:/var/www/html
      #- ./plugin-name/:/var/www/html/wp-content/plugins/plugin-name
      #- ./theme-name/:/var/www/html/wp-content/themes/theme-name
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME_FILE: /run/secrets/mysql_name
      WORDPRESS_DB_USER_FILE: /run/secrets/mysql_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    volumes:
      - ./secrets/:/run/secrets
      - ./config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME_FILE: /run/secrets/mysql_name
      WORDPRESS_DB_USER_FILE: /run/secrets/mysql_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
    depends_on:
      - db
      - wp

  pma:
    image: phpmyadmin:latest  # https://hub.docker.com/_/phpmyadmin
    container_name: pma
    ports:
      - 127.0.0.1:8010:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER_FILE: /run/secrets/mysql_user
      PMA_PASSWORD_FILE: /run/secrets/mysql_password
    links:
      - db:db
    volumes:
     - ./secrets/:/run/secrets
     - ./config/pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
     - ./config/pma_config.php:/etc/phpmyadmin/config.user.inc.php

  db:
    image: mysql:8
    restart: always
    container_name: mysql
    ports:
      - 127.0.0.1:3306:3306
    command: [
        # '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./secrets/:/run/secrets
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/mysql_name
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

volumes:
  wp_data:
  db_data:
